In [2]:
import numpy as np


In [3]:
a=np.random.randint(1,20,size=[3,4])
a

array([[ 6,  7,  6,  7],
       [ 6, 19,  7,  6],
       [ 7, 17, 16,  5]])

In [7]:
b=np.array([1,2,3])
a+b


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [4]:
m=np.max(a,axis=1)
m

array([ 7, 19, 17])

In [6]:
a-m.reshape(-1,1)

array([[ -1,   0,  -1,   0],
       [-13,   0, -12, -13],
       [-10,   0,  -1, -12]])

In [15]:
c=np.array([1,2,3,4])
c.shape
d=c.reshape(-1,4)
d.shape

(1, 4)