In [1]:
import numpy as np
import linerreg
import npas
import matplotlib.pyplot as plt


In [2]:
X = np.random.randint(low=1, high=20, size=[20, 5])
X_train=X[0:10,:]
X_test=X[11:,:]
X_train_t=npas.linerreg_feature_scaling(X_train)
X_test_t=npas.linerreg_feature_scaling(X_test)
X=npas.add_right_ones(X)
X_train_t=npas.add_right_ones(X_train_t)
X_test_t=npas.add_right_ones(X_test_t)
X,X_train_t,X_test_t

(array([[ 9, 16, 14, 18, 15,  1],
        [10, 15,  7, 10,  7,  1],
        [ 7, 18, 11,  4,  7,  1],
        [11, 15,  3, 17, 13,  1],
        [ 6,  4,  3,  2, 11,  1],
        [11,  3, 16, 19, 11,  1],
        [10, 16, 16, 12,  9,  1],
        [ 8, 12, 11, 19,  8,  1],
        [ 4,  8, 10,  2,  4,  1],
        [ 9, 16, 13,  3, 16,  1],
        [11, 15, 19, 11,  8,  1],
        [13,  9,  7, 17,  6,  1],
        [10, 15, 13, 18, 10,  1],
        [15,  5, 14, 18,  7,  1],
        [ 8, 10, 17,  3, 17,  1],
        [ 4,  8,  6, 19, 11,  1],
        [ 1,  6,  4, 11, 14,  1],
        [19,  5,  7, 12,  6,  1],
        [11, 19, 13,  2, 11,  1],
        [10,  9,  2, 13, 19,  1]]),
 array([[0.71, 0.87, 0.85, 0.94, 0.92, 1.  ],
        [0.86, 0.8 , 0.31, 0.47, 0.25, 1.  ],
        [0.43, 1.  , 0.62, 0.12, 0.25, 1.  ],
        [1.  , 0.8 , 0.  , 0.88, 0.75, 1.  ],
        [0.29, 0.07, 0.  , 0.  , 0.58, 1.  ],
        [1.  , 0.  , 1.  , 1.  , 0.58, 1.  ],
        [0.86, 0.87, 1.  , 0.59, 0.42, 1. 

In [9]:
Theta = np.array([2, 4, 23, 7, 14, 3], dtype=float)
Y_true = np.dot(X, Theta)
learn_rate = 0.05
iter_times = 20000
Init_theta = np.array([0, 0, 0, 0, 0, 0], dtype=float)
test = linerreg.Linerreg(X_train_t, Y_true[:10], learn_rate, iter_times, Init_theta)
Theta_predict=test.update_wb()
Theta_predict

array([ 15.53925651,  58.11891379, 298.25440742, 118.44912658,
       167.99983842, 162.32365382])

In [10]:
Y_test_predict=np.round(np.dot(X_test_t,Theta_predict),2)
print("Y真实值是：",Y_true[11:])
print("Y预测值是：",Y_test_predict)


Y真实值是： [429. 648. 599. 709. 468. 394. 390. 568. 462.]
Y预测值是： [392.26 592.5  537.76 637.49 439.97 372.1  346.18 510.69 431.93]


In [ ]:
plt.plot(Y_true[11:], color='blue')
plt.plot(Y_test_predict, color='red')


# 显示图像
plt.show()